_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Welcome:index }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo

# FOS\UserBundle
fos_user_security:
    resource: @FOSUserBundle/Resources/config/routing/security.xml

fos_user_user:
    resource: @FOSUserBundle/Resources/config/routing/user.xml
    prefix: /user

asso_test:
    resource:  "@AssoTestBundle/Resources/config/routing.yml"
    prefix:    /test