AssoSite:
    pattern:  /
    defaults: { _controller: AssoBookBundle:Book:index }

asso_book_new:
    pattern:  /new
    defaults: { _controller: AssoBookBundle:Book:new }

asso_book_show:
    pattern:  /show/{id}
    defaults: { _controller: AssoBookBundle:Book:show }

asso_book_newAccount:
    pattern:  /newAccount
    defaults: { _controller: AssoBookBundle:Book:newAccount }

asso_book_showAccount:
    pattern:  /showAccount/{id}
    defaults: { _controller: AssoBookBundle:Book:showAccount }

asso_book_delete_entry:
    pattern:  /deleteEntry/{id}.{_format}
    defaults: { _controller: AssoBookBundle:Book:deleteEntry, _format: html }
    requirements:
        _format: json

asso_book_list_entries:
    pattern:  /listEntries.{_format}
    defaults: { _controller: AssoBookBundle:Book:listEntries, _format: html }
    requirements:
        _format: json