asso_book_new_entry:
    pattern:  /new
    defaults: { _controller: AssoBookBundle:Book:new_entry }

asso_book_new_account:
    pattern:  /newAccount
    defaults: { _controller: AssoBookBundle:Book:new_account }

asso_book_show_account:
    pattern:  /showAccount/{id}
    defaults: { _controller: AssoBookBundle:Book:show_account }

asso_book_delete_entry:
    pattern:  /deleteEntry/{id}.{_format}
    defaults: { _controller: AssoBookBundle:Book:delete_entry, _format: html }
    requirements:
        _format: json

asso_book_edit_entry:
    pattern:  /editEntry/{id}
    defaults: { _controller: AssoBookBundle:Book:edit_entry, _format: html }

asso_book_list_entries:
    pattern:  /listEntries.{_format}
    defaults: { _controller: AssoBookBundle:Book:list_entries, _format: html }
    requirements:
        _format: json

asso_book_home:
    pattern:  /listEntries
    defaults: { _controller: AssoBookBundle:Book:list_entries }

asso_book_actions:
    pattern:  /actions.{_format}
    defaults: { _controller: AssoBookBundle:Book:actions, _format: html }
    requirements:
        _method: post
        _format: json